// <auto-generated />
namespace Practice.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddColumnIsDeletedToTableEmployeeDepartmentHistory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddColumnIsDeletedToTableEmployeeDepartmentHistory));
        
        string IMigrationMetadata.Id
        {
            get { return "201907231123436_AddColumnIsDeletedToTableEmployeeDepartmentHistory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
